### ISSUE TITLE
修改一些东西可能会更好

### ISSUE THREAD

**Issue by ghost** [cbsfly/CBSSegmentView#1]
1.headView里面的布局,我认为复杂化了,直接在ScrollerViewContentView添加N个button,然后额外添加下划线,这样就可以实现,避免再次加入一个scrollerView的麻烦
2.注意到,每次切换都会重新创建一个VC,这里如果能做到"已经创建过的就直接使用,没创建过的就创建"会更好.
3.代码写的不错,思路很清晰,如果能再把一些能封装起来的控件进行封装,那又会是更好.

**Comment by cbsfly** [comment]
1.一个ScrollerView的话就做不到 字的颜色也时时关联的移动
2.现在也是按需加载，创建好后会将数组里计数器置1，只有为0才会加载
3.有时间我会改进，谢谢建议

**Comment by sffernando** [comment]
关于第二点，每次判断加载，最多初始化一个的思路巧妙，学习到了。这儿还有点疑惑，就是现在有多少标题，最终还是会创建多少个viewController，这其中能不能进行重用呢，能否只用三个就可以达到这种效果呢？

**Comment by celljay86714** [comment]
我比较赞同  【已经创建过的就直接使用,没创建过的就创建】，你会发现当一个vc没创建的时候划过去的是白板然后才创建对应的vc，这在项目级别里面肯定是无法满足产品需求的。
第二 没有做可复用性，继续优化吧

**Comment by cbsfly** [comment]
@celljay86714 @zhangyabinzyb 这种控件复用的适用场景几乎没有吧。。例子只是为了方便复用了一下，真正的工程中应该没有标签页中有两个完全一样的界面吧。  如果一定要复用可以考虑哈希表做个映射，但我觉得完全没必要。

@celljay86714 我观察了一下现在世面上的应用包括网易云音乐，爱奇艺都是滚到那个页面再进行加载的，只不过他们加个一个加载的动画而已，如果按你说的需要一次性加载至少三个页面，那将造成大量的资源浪费很很多不必要的网络请求，得不偿失。
